export enum Currency {
  AUD = "AUD",
  BGN = "BGN",
  BRL = "BRL",
  CAD = "CAD",
  CHF = "CHF",
  CNY = "CNY",
  CZK = "CZK",
  DKK = "DKK",
  EUR = "EUR",
  GBP = "GBP",
  HKD = "HKD",
  HRK = "HRK",
  HUF = "HUF",
  IDR = "IDR",
  ILS = "ILS",
  INR = "INR",
  ISK = "ISK",
  JPY = "JPY",
  KRW = "KRW",
  MXN = "MXN",
  MYR = "MYR",
  NOK = "NOK",
  NZD = "NZD",
  PHP = "PHP",
  PLN = "PLN",
  RON = "RON",
  RUB = "RUB",
  SEK = "SEK",
  SGD = "SGD",
  THB = "THB",
  TRY = "TRY",
  USD = "USD",
  ZAR = "ZAR",
}

export const CurrencyList: CurrencyDetail[] = [
  { code: Currency.AUD, name: "Australian Dollar" },
  { code: Currency.BGN, name: "Bulgarian Lev" },
  { code: Currency.BRL, name: "Botswana Pula" },
  { code: Currency.CAD, name: "Canadian Dollar" },
  { code: Currency.CHF, name: "Swiss Franc" },
  { code: Currency.CNY, name: "Chinese Yuan Renminbi" },
  { code: Currency.CZK, name: "Czech Koruna" },
  { code: Currency.DKK, name: "Danish Krone" },
  { code: Currency.EUR, name: "European Euro" },
  { code: Currency.GBP, name: "Pound Sterling" },
  { code: Currency.HKD, name: "Hong Kong Dollar" },
  { code: Currency.HRK, name: "Croatian Kuna" },
  { code: Currency.HUF, name: "Hungarian Forint" },
  { code: Currency.IDR, name: "Indonesian Rupiah" },
  { code: Currency.ILS, name: "Israeli New Shekel" },
  { code: Currency.INR, name: "Indian Rupee", symbol: "₹" },
  { code: Currency.ISK, name: "Icelandic Krona" },
  { code: Currency.JPY, name: "Japanese Yen" },
  { code: Currency.KRW, name: "South Korean Won" },
  { code: Currency.MXN, name: "Mexican Peso" },
  { code: Currency.MYR, name: "Malaysian Ringgit" },
  { code: Currency.NOK, name: "Norwegian Krone" },
  { code: Currency.NZD, name: "New Zealand Dollar" },
  { code: Currency.PHP, name: "Philippine Peso" },
  { code: Currency.PLN, name: "Polish Zloty" },
  { code: Currency.RON, name: "Romanian Leu" },
  { code: Currency.RUB, name: "Russian Ruble" },
  { code: Currency.SEK, name: "Swedish Krona" },
  { code: Currency.SGD, name: "Singapore Dollar" },
  { code: Currency.THB, name: "Thai Baht" },
  { code: Currency.TRY, name: "Turkish Lira" },
  { code: Currency.USD, name: "United States Dollar", symbol: "$" },
  { code: Currency.ZAR, name: "South African Rand" },
];

export interface CurrencyDetail {
  code: Currency;
  name: string;
  symbol?: string;
}
