import {
  faHospital,
  faHeart,
  faCreditCard,
  faTrashAlt,
  faSnowflake,
  faMoon,
  faNewspaper,
  faClipboard,
  faStar,
} from "@fortawesome/free-regular-svg-icons";

import {
  faUtensils,
  faBaby,
  faBirthdayCake,
  faBus,
  faShoppingCart,
  faBandAid,
  faBaseballBall,
  faBath,
  faBeer,
  faBook,
  faBookmark,
  faBroadcastTower,
  faBroom,
  faBrush,
  faBuilding,
  faHome,
  faBookOpen,
  faBusinessTime,
  faCalendar,
  faCapsules,
  faCar,
  faCarBattery,
  faCarCrash,
  faCarrot,
  faCat,
  faChair,
  faChargingStation,
  faCocktail,
  faCoffee,
  faCompactDisc,
  faCookie,
  faCookieBite,
  faCouch,
  faCross,
  faDice,
  faDog,
  faDollarSign,
  faDonate,
  faDove,
  faDraftingCompass,
  faDragon,
  faDrum,
  faDumbbell,
  faEgg,
  faFaucet,
  faMale,
  faFemale,
  faFilm,
  faFire,
  faFireExtinguisher,
  faFish,
  faFootballBall,
  faGift,
  faGifts,
  faFutbol,
  faGasPump,
  faGamepad,
  faGlassCheers,
  faGlassMartini,
  faGlassMartiniAlt,
  faGlassWhiskey,
  faGopuram,
  faGraduationCap,
  faGuitar,
  faHamburger,
  faHiking,
  faIceCream,
  faIdBadge,
  faIdCard,
  faIdCardAlt,
  faInfinity,
  faLaptop,
  faLightbulb,
  faLifeRing,
  faMobile,
  faPaw,
  faPepperHot,
  faPiggyBank,
  faPills,
  faPizzaSlice,
  faPlane,
  faPray,
  faRobot,
  faRoad,
  faRupeeSign,
  faRoute,
  faRocket,
  faHeartBroken,
  faHeartbeat,
  faShippingFast,
  faShoePrints,
  faSeedling,
  faShuttleVan,
  faShower,
  faSkating,
  faSmoking,
  faSmokingBan,
  faSnowman,
  faSocks,
  faSoap,
  faSpa,
  faSpellCheck,
  faSpider,
  faSprayCan,
  faStamp,
  faStore,
  faStoreAlt,
  faSubway,
  faSuitcaseRolling,
  faSyringe,
  faTableTennis,
  faTablet,
  faTaxi,
  faTicketAlt,
  faTools,
  faToolbox,
  faTree,
  faTrophy,
  faTruck,
  faTshirt,
  faUmbrella,
  faUniversity,
  faUserAstronaut,
  faUserGraduate,
  faUserMd,
  faUserNinja,
  faUserSecret,
  faWineBottle,
  faWineGlass,
  faWineGlassAlt,
  faWrench,
  faWallet,
  faVrCardboard,
  faVial,
  faVials,
  faVenus,
  faVenusDouble,
  faVenusMars,
  faMarsDouble,
  faVideo,
  faVihara,
  faYinYang,
  faWonSign,
  faYenSign,
  faEuroSign,
  faLiraSign,
  faPoundSign,
  faRubleSign,
  faShekelSign,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-common-types";

export const icons: Icon[] = [
  { name: "Hospital", icon: faHospital, tags: ["medicine", "hospital", "medical", "health", "emergency"] },
  { name: "Bandaid", icon: faBandAid, tags: ["medicine", "hospital", "medical", "health", "bandaid", "fracture"] },
  { name: "Medicine", icon: faCapsules, tags: ["medicine", "hospital", "disease", "cure", "health"] },
  { name: "Medicine2", icon: faVials, tags: ["medicine", "cure", "health", "hospital", "disease"] },
  {
    name: "Groceries",
    icon: faCarrot,
    tags: ["carrot", "groceries", "vegetables", "eat"],
  },
  {
    name: "Dinner",
    icon: faUtensils,
    tags: ["eat", "spoon", "vessels"],
  },
  {
    name: "Baby",
    icon: faBaby,
  },
  {
    name: "Home",
    icon: faHome,
  },
  {
    name: "NewsPaper",
    icon: faNewspaper,
  },
  {
    name: "University",
    icon: faUniversity,
  },
  {
    name: "Books",
    icon: faBook,
  },
  {
    name: "Book2",
    icon: faBookOpen,
  },
  {
    name: "Book3",
    icon: faBookmark,
  },
  {
    name: "Snow Flake",
    icon: faSnowflake,
  },
  {
    name: "Heart",
    icon: faHeart,
  },
  {
    name: "Credit Card",
    icon: faCreditCard,
  },
  {
    name: "Trash",
    icon: faTrashAlt,
  },
];

export interface Icon {
  name: string;
  icon: IconDefinition;
  tags?: string[];
}
